config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  get "profile", to: "profiles#edit", as: :profile
  post "profile", to: "profiles#update", as: :update_profile

  resources :matches, only: [:index, :show] do
    member do
      get :show_react
    end
    resources :approvals, only: [:update]
    resources :chats, only: [:index, :create]
  end

  get "browse", to: "matches#show", as: :browse

  authenticated :user do
    root to: "matches#show", as: :user_root
  end

  root to: "home#index"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :ensure_profile_completed

  def edit
  end

  def update
    if current_user.update profile_params
      redirect_to profile_path, notice: "Your profile has been updated. ;)"
    else
      redirect_to profile_path, notice: "Your profile couldn't be updated :'("
    end
  end

  private
    def profile_params
      params.permit(:code_sample)
    end
end

app/views/profiles/edit.html.erb
<h1>Your Profile</h1>

<div class="col-md-6">
  <%= form_tag update_profile_path, method: :post do %>
    <div class="form-group">
    <%= link_to "https://help.github.com/articles/github-flavored-markdown/" do %>
      <p class="small">Uses Github-flavored markdown</p>
    <% end %>
      <%= text_area_tag :code_sample, current_user.code_sample, placeholder: "Add your sexy code sample here", class: "form-control", rows: 10 %>
    </div>
    <%= submit_tag "Update My Sexy Code Sample", class: "btn btn-success btn-lg" %>
  <% end %>
</div>

<div class="col-md-6">
  <p class="small">Preview</p>
  <% if current_user.code_sample.presence %>
    <div class="card card-block">
      <%= markdownify(current_user.code_sample) %>
    </div>
  <% end %>
</div>