config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  get "profile", to: "profiles#edit", as: :profile
  post "profile", to: "profiles#update", as: :update_profile

  resources :matches, only: [:index, :show] do
    member do
      get :show_react
    end
    resources :approvals, only: [:update]
    resources :chats, only: [:index, :create]
  end

  get "browse", to: "matches#show", as: :browse

  authenticated :user do
    root to: "matches#show", as: :user_root
  end

  root to: "home#index"
end

app/models/match.rb
class Match < ActiveRecord::Base
  include ActiveModel::Serialization

  has_many :approvals
  has_many :users, through: :approvals
  has_many :chats

  enum status: [:pending, :made, :avoided, :engaged]

  def partner_for(user)
    (users - [user]).first
  end

  def approval_for(user)
    approvals.where(user: user).first
  end

  def update_status!
    decision = approvals.pluck(:given)
    if decision == [true, true]
      made!
    elsif decision.include?(nil)
      pending!
    elsif decision.include(false)
      avoided!
    elsif chats.any?
      engaged!
    else
      raise InappropropriateStatusException
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_match
  before_action :set_partner
  before_action :set_approval

  def index
    @matches = current_user.matches.made + current_user.matches.engaged
    unless @matches.any?
      redirect_to browse_path, notice: "Look, ya gotta find yoself some friends before you're allowed into that section."
    end
  end

  def show
  end

  def show_react
  end

  private
    def set_match
      if params[:id].present?
        @match = Match.find(params[:id])
      else
        @match = MatchMaker.new(current_user).matchmake
      end
    end

    def set_partner
      @partner = @match.partner_for(current_user)
    end

    def set_approval
      @approval = @match.approval_for(current_user)
    end

    def no_match?
      @match.class == "Match"
    end
end

app/views/matches/_engaged.html.erb
<%= render partial: "match" %>

app/views/matches/_made.html.erb
<%= render partial: "match" %>

app/views/matches/_match.html.erb
<div class="row">
  <%= react_component('ChatContainer', {chats_url: match_chats_url(@match), create_chat_url: match_chats_url(@match)} ) %>
  <div class="col-md-6">
  <h2 class="text-center"><span class="text-info"><%= @partner.username %></span></h2>
    <div class="card card-block">
      <p class="card-text"><%= markdownify(@partner.code_sample) %></p>
    </div>
  </div>
</div>

app/views/matches/_nothing.html.erb
<div class="row">
  <h2 class="text-center">pair with <span class="text-info">Nobody</span> ?</h2>

  <div class="col-md-8 col-md-offset-2">
    <div class="card card-block">
      <p class="card-text">There's nobody left for you to decide on, much like my dating life.</p>
      <p class="card-text">If you want to escape a lifetime of crushing loneliness, tell your friends about this site.</p>
    </div>
  </div>
</div>

app/views/matches/_pending.html.erb
<div class="row">
  <h2 class="text-center">pair with <span class="text-info"><%= @partner.username %></span> ?</h2>
  <div class="col-md-2">
    <%= form_for [@match, @approval] do |f| %>
      <%= f.hidden_field :given, value: false %>
      <%= f.submit "hell naw", class: "btn btn-danger" %>
    <% end %>
  </div>

  <div class="col-md-8">
    <div class="card card-block">
      <p class="card-text"><%= markdownify(@partner.code_sample) %></p>
    </div>
  </div>

  <div class="col-md-2">
    <%= form_for [@match, @approval] do |f| %>
      <%= f.hidden_field :given, value: true %>
      <%= f.submit "omg yes", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/matches/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table">
    <thead>
      <tr>
        <th>person</th>
        <th>messages</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @matches.each do |match| %>
      <tr>
        <th scope="row"><%= link_to match.partner_for(current_user).username, match_path(match) %></th>
        <td><%= match.chats.count %></td>
        <td class="text-muted"><%= time_ago_in_words match.created_at %> ago</td>
      </tr>
    <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/matches/show.html.erb
<div clas="row">
  <%= render partial: @match.status %>
</div>

app/views/matches/show_react.html.erb
<div class="row">
  <div class="col-md-6">
  <h2><span class="text-muted">Chat</span></h2>
    <div class="card card-block">
      <div id="chat-messages">
        <%= render @match.chats %>
      </div>
      <div>
        <%= form_for [@match, Chat.new] do |f| %>
          <div class="form-group">
            <%= f.text_area :message, placeholder: "Your message here", autofocus: true, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit "chat", class: "btn btn-default" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
  <h2 class="text-center"><span class="text-info"><%= @partner.username %></span></h2>
    <div class="card card-block">
      <p class="card-text"><%= @partner.code_sample %></p>
    </div>
  </div>
</div>

<%= react_component('ChatContainer', {chats_url: match_chats_url(@match), create_chat_url: match_chats_url(@match)} ) %>